# Cloudflare Pages 配置
# 基于 OpenNext.js for Cloudflare Pages 的官方推荐配置
# 注意：此文件仅包含配置模板，实际密钥通过 Cloudflare Dashboard 设置

name = "umuo-app"
# Pages 项目不需要 main 函数，由 Functions 处理
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

# Pages 构建输出目录
pages_build_output_dir = ".open-next/assets"

# Pages 环境配置
[env.production]
name = "umuo-app-pages"

[env.preview]
name = "umuo-app-pages-preview"

# 调试和分析
[observability]
enabled = true
